language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

install:
  - npm install

services:
  - mongodb

env:
  global:
  - NODE_ENV=test

before_script:
  - use testing

script:
  - npm test
after_success: 
  - npm run coveralls

notifications:
  email: false
 